<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetTargetFramework)</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<PackageOutputPath>.\..\..\nuget.push\KSW.UI.WPF</PackageOutputPath>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\alert-circle.png" />
	  <None Remove="Resources\Images\alert.png" />
	  <None Remove="Resources\Images\checkbox-circle.png" />
	  <None Remove="Resources\Images\error.png" />
	  <None Remove="Resources\Images\information.png" />
	  <None Remove="Resources\Images\question.png" />
	  <None Remove="Resources\Images\warning.png" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Bold.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-ExtraLight.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Heavy.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Light.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Medium.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Normal.otf" />
	  <None Remove="Resources\SourceHanSans\SourceHanSansSC-Regular.otf" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Bold.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-ExtraLight.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Heavy.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Light.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Medium.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Normal.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\SourceHanSans\SourceHanSansSC-Regular.otf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\KSW.Core\KSW.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Images\alert-circle.png" />
	  <Resource Include="Resources\Images\alert.png" />
	  <Resource Include="Resources\Images\checkbox-circle.png" />
	  <Resource Include="Resources\Images\error.png" />
	  <Resource Include="Resources\Images\information.png" />
	  <Resource Include="Resources\Images\question.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Views\ProcessBarDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

</Project>
