<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	  <PackageOutputPath>.\..\..\nuget.push\KSW.ObjectMapping.AutoMapper</PackageOutputPath>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\Ksw.Core\KSW.Core.csproj" />
  </ItemGroup>

</Project>
